#!/bin/sh
#
# BSD Router Project: FreeVRRPd startup script
#
# Copyright (c) 2009, The BSDRP Development Team 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# PROVIDE: freevrrpd
# REQUIRE: NETWORKING
# KEYWORD: nojail
#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# freevrrpd_enable="YES"
#

. /etc/rc.subr

name="freevrrpd"
rcvar=`set_rcvar`

start_cmd="freevrrpd_start"
stop_cmd="freevrrpd_stop"

freevrrpd_start()
{
    [ -x /usr/local/sbin/freevrrpd ] && /usr/local/sbin/freevrrpd && echo -n ' freevrrpd'
    exit 0
}

freevrrpd_stop()
{
    killall freevrrpd > /dev/null 2>&1 && echo -n ' freevrrpd'
    exit 0
}

load_rc_config $name
run_rc_command "$1"
