--- Makefile.old	2010-06-23 10:41:29.000000000 +0200
+++ Makefile	2010-06-23 10:57:18.000000000 +0200
@@ -22,7 +22,7 @@
 
 CONFLICTS=	openbgpd-[0-9]* zebra-0*
 
-USE_AUTOTOOLS=	libtool:22
+USE_AUTOTOOLS=	libtool:22 autoheader:262 autoconf:262
 USE_GMAKE=		yes
 USE_LDCONFIG=		yes
 USE_PERL5_BUILD=	yes
