#!/bin/sh
#
# BSD Router Project:	autosaved Init script 
# http://bsdrp.net
#
# Copyright (c) 2017, The BSDRP Development Team 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

. /etc/rc.subr

name=autosave
rcvar=${name}_enable

autosave_stop()
{
	if [ -f ${pidfile} ]; then
		rc_pid=$(check_pidfile $pidfile ${name})
		kill -TERM $rc_pid
		wait_for_pids $rc_pid
	fi
}

stop_postcmd()
{
	rm -f "$pidfile" || warn "Could not remove $pidfile."
}

autosave_status()
{
	rc_pid=$(check_pidfile $pidfile ${name})

	if [ -z "$rc_pid" ]; then
		[ -n "$rc_fast" ] && return 0
		if [ -n "$pidfile" ]; then
			echo "${name} not running? (check $pidfile)."
		else
			echo "${name} not running?"
		fi
		return 1
	fi
	echo "${name} is running as pid ${rc_pid}"
}

# pidfile
pidfile="/var/run/${name}.pid"
rc_pid=$(check_pidfile $pidfile ame)

# command and arguments
procname="/usr/local/sbin/autosaved"
command="/usr/sbin/daemon"

# run this last
stop_cmd="autosave_stop"
stop_postcmd="stop_postcmd"

load_rc_config ${name}

command_args="-f -p ${pidfile} ${procname}"

run_rc_command "$1"
