#!/bin/sh
#
# BSD Router Project:	autosave Init script
# http://bsdrp.net
#
# Copyright (c) 2017, The BSDRP Development Team
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# PROVIDE: autosave
# REQUIRE: DAEMON
# KEYWORD: shutdown

. /etc/rc.subr

name=autosave
rcvar=${name}_enable
stop_cmd="${name}_stop"

autosave_stop () {
	# autosave is a simple shell script with fswatch in a loop
	# for stoping autosave, we need to stop fswatch and the autosave script
	autosave_pid=$(pgrep -f "/bin/sh /usr/local/sbin/autosave")
	fswatch_pid=$(pgrep -f "fswatch -1dr /etc")
	if [ -n "${autosave_pid}" ] && [ -n "${fswatch_pid}" ]; then
		kill ${autosave_pid} ${fswatch_pid} || logger Failed to kill autosave
	fi
}

pidfile="/var/run/${name}.pid"

command="/usr/sbin/daemon"

load_rc_config ${name}
: ${autosave_enable="NO"}

command_args="-f -P ${pidfile} -u root /usr/local/sbin/autosave"

run_rc_command "$1"
