#!/bin/sh
# Bind bxe(4) interrupt threads to different cores
# Adapted from same chelsio RC script by farrokhi@FreeBSD.org

# PROVIDE:	bxe_affinity
# REQUIRE:	FILESYSTEMS netif
# KEYWORD:	nojail

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# bxe_affinity_enable (bool):   Set to NO by default.
#               Set it to YES to bind interrupt threads to different cores
# bxe_affinity_avoidncpu (int):  0 by default.
#		Set to number of CPU to exclude from binding

. /etc/rc.subr

name="bxe_affinity"
rcvar=${name}_enable

start_cmd="bxe_affinity_start"

bxe_affinity_start()
{
	# Need a bxe NIC
	NQ=$(/sbin/sysctl -ni dev.bxe.0.state)
	if [ -z "${NQ}" ]; then
		echo "No bxe NIC detected"
		exit 0;
	fi

	# Work with 2 CPU minimum
	NCPU=$(/sbin/sysctl -n hw.ncpu)
	if [ ${NCPU} -le 2 ]; then
		echo "Not enought CPU detected"
		exit 0
	fi

	# Exclude some CPU from binding
	NCPU=$((NCPU - ${bxe_affinity_avoidncpu}))
	CPU=0
	nics=$(/sbin/sysctl dev.bxe. | grep -c fw_version)
	for i in $(seq 0 $((nics - 1))); do
		for IRQ in `/usr/bin/vmstat -ai |\
			/usr/bin/sed -nE "/bxe${i}:fp./ s/irq([[:digit:]]+):.*/\1/p"`; do
			echo "Bind bxe${i} IRQ ${IRQ} to CPU ${CPU}"
			/usr/bin/cpuset -l ${CPU} -x ${IRQ}
			CPU=$(((CPU + 1) % NCPU))
		done
		CPU=0
	done
}

load_rc_config $name

: ${bxe_affinity_enable="NO"}
: ${bxe_affinity_avoidncpu=0}

run_rc_command "$1"
