#!/bin/sh
# Bind Chelsio interrupt threads to different cores (melifaro@FreeBSD.org)

# PROVIDE:      chelsio_affinity
# REQUIRE:      FILESYSTEMS netif
# KEYWORD:      nojail

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# chelsio_affinity_enable (bool):   Set to YES by default.
#               Set it to YES to bind interrupt threads to different cores
# chelsio_affinity_avoidncpu (int):  0 by default.
#		Set to number of CPU to exclude from binding

. /etc/rc.subr

name="chelsio_affinity"
rcvar=${name}_enable

start_cmd="chelsio_affinity_start"

chelsio_affinity_start()
{
	# Need a Chelsio NIC
	NQ=$(/sbin/sysctl -ni dev.cxl.0.nrxq)
	if [ -z "${NQ}" ]; then
		echo "No Chelsio NIC port detected"
		exit 0;
	fi

	# Work with 2 CPU minimum
	NCPU=$(/sbin/sysctl -n hw.ncpu)
	if [ ${NCPU} -le 2 ]; then
		echo "Not enought CPU detected"
		exit 0
	fi

	# Exclude some CPU from binding
	NCPU=$((NCPU - ${chelsio_affinity_avoidncpu}))
	CPU=0
	cxl=$(sysctl dev.cxl. | grep -c nrxq)
	for i in $(seq 0 $((cxl - 1))); do
		for IRQ in `/usr/bin/vmstat -ai |\
			/usr/bin/sed -nE "/t5nex0:${i}a/s/irq([[:digit:]]+):.*/\1/p"`; do
			echo "Bind t5nex0:${i}a IRQ ${IRQ} to CPU ${CPU}"
			/usr/bin/cpuset -l ${CPU} -x ${IRQ}
			CPU=$(((CPU + 1) % NCPU))
		done
		CPU=0
	done
}

load_rc_config $name

: ${chelsio_affinity_enable="NO"}
: ${chelsio_affinity_avoidncpu=0}

run_rc_command "$1"

