#!/bin/sh
#
# BSD Router Project: Disable LRO and TSO feature on all interface
#
# Copyright (c) 2014, The BSDRP Development Team 
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# PROVIDE: disablelrotso
# REQUIRE: netif
# KEYWORD: nojail
#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# disablelrotso_enable="YES"
#

. /etc/rc.subr

disablelrotso=${disablelrotso_enable-"NO"}

name="disablelrotso"
rcvar=${name}_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"

# Get the list of Ethernet devices
DETECTED_DEVICES=`ifconfig -l "ether"`

disablelrotso_start()
{
	# Disable LRO and TSO on all detected interfaces:
	for DETECTED in ${DETECTED_DEVICES}
	do
		echo -n "Disabling TSO, LRO and VLAN_HWTSO on: ${DETECTED}..."
		ifconfig ${DETECTED} -tso4 -tso6 -lro -vlanhwtso && echo "done" || echo "failed"
	done
exit 0
}

disablelrotso_stop()
{
	# Re-enable LRO and TSO on all interface that support it:
	for DETECTED in ${DETECTED_DEVICES}
	do
		echo -n "Re-enabling TSO, LRO and VLAN_HWTSO on : ${DETECTED}..."
		ifconfig ${DETECTED} tso4 tso6 lro vlanhwtso && echo "done" || echo "failed"
	done
exit 0
}

load_rc_config $name
run_rc_command "$1"
