#!/bin/sh
#
# Script from http://www.freebsd.org/cgi/query-pr.cgi?pr=kern/164475
# PROVIDE: fixgre
# REQUIRE: LOGIN NETWORKING

. /etc/rc.subr

name="fixgre"
rcvar=${name}_enable

start_cmd="start_cmd"

start_cmd () {
for i in `ifconfig | grep -E 'gre[0-9]+:' | awk -F: '{print $1}'`
do
ifconfig $i up
done
}

load_rc_config $name
run_rc_command "$1"
