#!/bin/sh
#
# PROVIDE: freevrrpd
# REQUIRE: NETWORKING
# KEYWORD: nojail
#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# freevrrpd_enable="YES"
#

. /etc/rc.subr

freevrrpd_enable=${freevrrpd_enable-"NO"}

name="freevrrpd"
rcvar=${name}_enable

command="/usr/local/sbin/${name}"
required_files="/usr/local/etc/${name}.conf"
required_modules="ng_socket ng_ether ng_bridge ng_eiface"

load_rc_config ${name}

run_rc_command "$1"
