#!/bin/sh
#
# BSD Router Project: Enable txabdicate on all iflib NIC interfaces
# (cause tx to abdicate instead of running to completion)
#
# Copyright (c) 2018, The BSDRP Development Team
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE PROJECT ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE PROJECT BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# PROVIDE: txabdicate
# REQUIRE: netif
# KEYWORD: nojail
#
# Add the following to /etc/rc.conf[.local] to enable this service
#
# txabdicate_enable="YES"
#

. /etc/rc.subr

txabdicate_enable=${txabdicate_enable-"NO"}

name="txabdicate"
rcvar=${name}_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"

# Get the list of detected devices
DETECTED_DEVICES=$(sysctl -a dev | grep tx_abdicate | cut -d ':' -f 1)

txabdicate_start()
{
	for DETECTED in ${DETECTED_DEVICES}; do
		echo "Enabling tx_abdicate on $(echo ${DETECTED}| cut -d '.' -f 2-3)"
		sysctl ${DETECTED}=1 > /dev/null 2>&1
	done
	exit 0
}

txabdicate_stop()
{
	for DETECTED in ${DETECTED_DEVICES}; do
		echo "Disabling tx_abdicate on $(echo ${DETECTED}| cut -d '.' -f 2-3)"
		sysctl ${DETECTED}=0 > /dev/null 2>&1
	done
	exit 0
}

load_rc_config $name

: ${txabdicate_enable="NO"}
run_rc_command "$1"
