#!/bin/sh
# Updating GeoIP database
set -eu

DATA_DIR="/usr/local/share/GeoIP"
TMPFS_DIR="/var/tmp/tmpfs"

# A usefull function (from: http://code.google.com/p/sh-die/)
die() { echo -n "EXIT: " >&2; echo "$@" >&2; exit 1; }

clean_exit () {
    umount /tmp/tmpfs
    mount -ur / || die "Can't remount in Read-Only mode"
}

echo "Downloading new GeoIP database..."
[ -d ${TMPFS_DIR} ] || mkdir ${TMPFS_DIR}
mount -t tmpfs tmpfs ${TMPFS_DIR} || die "Can't mount tmpfs file system"
fetch -o ${TMPFS_DIR}/GeoLite2-City.mmdb.gz http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz || die "Can't download new database"
mount -uw / || die "Can't re-mount / in Read-Write mode"
trap "echo 'Running exit trap code' ; clean_exit" 1 2 15 EXIT
rm ${DATA_DIR}/GeoLite2-City.mmdb || echo "Can't rm old database"
gzcat ${TMPFS_DIR}/GeoLite2-City.mmdb.gz > ${DATA_DIR}/GeoLite2-City.mmdb || echo "Can't gunzip new database"
clean_exit
trap - 1 2 15 EXIT
echo "GeoIP database updated!"
