#!/bin/sh
#
# System tool for BSD Router Project 
# http://bsdrp.net
#
# Copyright (c) 2009-2015, The BSDRP Development Team
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# Uncomment for enable the debug mode:
#set -xv

# Strict script
set -e
#set -u

# A usefull function (from: http://code.google.com/p/sh-die/)
die() { echo -n "EXIT: " >&2; echo "$@" >&2; exit 1; }

# Display help
usage () {
	echo "BSD Router Project: system tool"
	case ${SECOND_OPTION} in
	check-vm)
		echo "Check if running under a Virtualized environnement (Qemu, VirtualBox, etc.)"
		echo "- [quiet] : Display only the warning"
		exit 0
		;;
	integrity)
		echo "Check system integrity using a reference mtree file"
		echo "The given file can be .mtree, .mtree.bz2 or .mtree.xz"
		echo "Note: Do not keep the reference mtree file on the router!"
		exit 0
		;;
	esac
	# value $0 is the name of the called script
	echo "Usage: $0 option"
	echo "  - expand-data-slice   : Permit to grow the /data partition size"
	echo "  - dual-console        : Configure the system for dual vga/serial console"
	echo "  - install [destination] : Install system to disk given in option"
	echo "  - integrity filename  : Check system integrity using the given reference file"
	echo "  - halt/stop           : Poweroff the system"
	echo "  - help/h [option]     : Display this help message. "
	echo "    if [option] given, display more detail about the option"
    echo "  - reboot/reload       : Restart the system"
	echo "  - rollback            : Revert to previous version"
	exit 0
}

# dual-console
# $1: Serial speed
dual_console () {
	[ $# -eq 0 ] && SERIAL_SPEED="" || SERIAL_SPEED=$1
	# We need to touch /boot/loader.conf.local for peristent changes
	grep -q Dh /boot.config && die "Dual console already configured"
	# Tell loader to use serial and vga console
	# Because there is no /boot.config we need to get the serial speed configured first
	# We will use the serial speed value already configured in /etc/ttys
	# But this value is set to "3wire" for FreeBSD 11, then we need to ask user for a value in this case
	if [ -z ${SERIAL_SPEED} ]; then
		egrep -q 'ttyu0.*std.*' /etc/ttys && \
		SERIAL_SPEED=`grep ttyu0 /etc/ttys | cut -d'.' -f 2 | cut -d '"' -f 1`
	fi
	# Check that we get something regarding serial speed
	[ -z "${SERIAL_SPEED}" ] && die "Can't determine serial speed from ttyu0
	on /etc/ttys, add the speed value to your command: 9600, 19200, 38400,
	   57600 and 115200"
	[ ${SERIAL_SPEED} -lt 9600 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
	[ ${SERIAL_SPEED} -gt 115200 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
    # On serial version, syscon devices was disabled, need to re-enable them:
    sed -i "" -e '/^ttyv[0-7]/s/off /on /' /etc/ttys
	mount -uw / || die "Can't mount / in RW mode"
	echo "-S${SERIAL_SPEED} -Dh" > /boot.config
	mount -ur / || die "Error for remounting / in RO mode"
}

# Check system integrity
integrity () {
	[ "${SECOND_OPTION}" = "" ] && die "ERROR: Reference mtree filename missing"
	[ ! -f ${SECOND_OPTION} ] && die "ERROR: File ${SECOND_OPTION} didn't exist."
	FILE_TYPE=`file ${SECOND_OPTION} | cut -d : -f 2`
    echo "./etc" > /tmp/mtree-exclude
    echo "./var" >> /tmp/mtree-exclude
    echo "./tmp" >> /tmp/mtree-exclude
    echo "./dev" >> /tmp/mtree-exclude
	if echo "${FILE_TYPE}" | grep -qi "ASCII text"; then
		cmd="mtree -f ${SECOND_OPTION} -X /tmp/mtree-exclude -p /"
	elif echo "${FILE_TYPE}" | grep -qi bzip; then
		# Warning, the bzipped file can be any type of file!
		cmd="bzcat ${SECOND_OPTION} | mtree -X /tmp/mtree-exclude -p /"
	elif echo "${FILE_TYPE}" | grep -qi xz; then
		cmd="xz -dc ${SECOND_OPTION} | mtree -X /tmp/mtree-exclude -p /"
	else
		die "Is the given reference mtree file a good mtree file ?"
	fi
	echo "Here is the modified files comparing to the reference mtree file:"
	eval $cmd
	
}

#ask to save configuration
ask_save () {	
	echo "Warning: Unsaved changes detected !"
	config diff
	echo -n "Do you want to save the configuration before to continue or abort ? (y/n/a): "
	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" -a "$USER_CONFIRM" != "a" ]; do
       	read USER_CONFIRM <&1
	done
	if [ "$USER_CONFIRM" = "y" ]; then
		config save	
	elif [ "$USER_CONFIRM" = "a" ]; then
		exit 0
	fi
}

#Install system to another disk
install () {
	label=`cut -d '/' -f 2 /etc/nanobsd.conf`
	boot_dev=`glabel status | grep ${label}s1 | awk '{ print $3; }'\  | cut -d s -f 1 | tail -n 1`
	sectors=`gpart show ${boot_dev} | grep '\- free \-' | tr -s ' ' | cut -d ' ' -f 2 | tail -n 1`
	disks=`sysctl -n kern.disks`
	[ $# -eq 0 ] && die "Missing destination disk (${disks})"
	[ ${boot_dev} == $1 ] && die "Source disk (${boot_dev}) is same as destination disk ($1), use another disk on this list: ${disks}"
	bytes=$(( 1 + ${sectors} / 2048 ))
	# Avoid the error message “the primary GPT table is corrupt or invalid.”
	# by cleaning the 2 GPT tables on the destination hard drive
	echo "Cleaning GPT tables on destination hard drive $1..."
	dd if=/dev/zero of=/dev/$1 bs=1m count=1 > /dev/null 2>&1 || die "Can't erase MBR/GPT table"
	dd if=/dev/zero of=/dev/$1 bs=1m oseek=`diskinfo $1 \
		| awk '{print int($3 / (1024*1024)) - 4;}'` > /dev/null 2>&1 || true
	echo "Copying ${bytes}MB from ${boot_dev} to $1..."
	dd if=/dev/${boot_dev} of=/dev/$1 bs=1M count=${bytes} || die "Meet error during install"
}

#When installed on bigger usb key or hard-drive
#Destroy the data partition and re-create a big one
expand_data_slice () {

	#Load the NANO_DRIVE (label) variable:
	. /etc/nanobsd.conf

	if [ `uname -m` = "sparc64" ]; then
		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a \
			 | awk '{ print $3; }' | sed 's/.$//'`
		die "Not supported: sparc64 for this function"
	else
		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a \
			 | awk '{ s=$3; sub(/s[12]a$/, "", s); print s; }'`
	fi
	label=`cut -d '/' -f 2 /etc/nanobsd.conf`

	if mount | grep -q "/data"; then
		die "/data is mounted, you need to unmount it"
	fi

	#free space
	FREE_SPACE=`gpart show ${boot_dev} | grep "\- free \-" | grep -v k \
			   | cut -d '-' -f 3 | tr -s ' '`
	[ -z "${FREE_SPACE}" ] && die "There is no space left on disk"
	echo "There is ${FREE_SPACE} available on your disk that can be use for /data"
	echo -n "Are you sure to repartition your disk ? (y/n)"
    	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
        	read USER_CONFIRM <&1
    	done
	[ "$USER_CONFIRM" = "n" ] && die "User cancel"

	# Using "gpart resize" + growfs  is too slow and create a bug with 
	# the geom label (pr=kern/165962)
	#

	# Backup the s4 (data) partion
	dump -0auf/tmp/s4.dump /dev/${NANO_DRIVE}s4 \
	|| die "ERROR: dumping ${NANO_DRIVE}s4 to /tmp failed"

	# Deleting partition s4
	# Need to check the partition delete on sparc64
	gpart delete -i 4 ${boot_dev} \
	|| die "Unable to gpart delete -i 4 ${boot_dev}"

	# Recreating s4 using full disk space
	gpart add -t freebsd ${boot_dev} \
	|| die "Unable gpart add -t freebsd ${boot_dev}"

	# Formatting the new partition (SUJ)
	# TO DO: Check if disks support TRIM and enable it
	LABEL=`cut -f 2 -d "/" /etc/nanobsd.conf`
	newfs -UjL ${LABEL}s4 ${boot_dev}s4 \
	|| die "Unable to newfs -UjL ${LABEL}s4 ${boot_dev}s4"

	# Restoring the dump
	[ -d /tmp/slice ] || mkdir -p /tmp/slice
	mount /dev/${NANO_DRIVE}s4 /tmp/slice \
	|| die "Unable to mount /dev/${NANO_DRIVE}s4 /tmp/slice"
	cd /tmp/slice
	restore rf /tmp/s4.dump || die "Unable to restore rf /tmp/s4.dump"
	[ -f /tmp/slice/restoresymtable ] && rm -rf /tmp/slice/restoresymtable
	[ -f /etc/dumpdates ] && rm -rf /etc/dumpdates

	cd
	umount /tmp/slice || die "Can't unmount /tmp/slice, but it's done"

	echo "Done"

}
#Revert to the other system partition
#Big part of this function came from the upgrade script
#TODO: Need to merge the upgrade script and this script
# 0. Ask a user confirmation
# 1. Check if there is a previous release
# 2. Mount the previous and update the fstab
# 3. Change the active slice and bootloader default choice	
rollback () {
	# Get the NANO_GLABEL_SYS variable
	NANO_GLABEL_SYS=`cut -d '/' -f 2 /etc/nanobsd.conf`
	# Get the NANO_GLABEL_SYS_FULL variable
	# (kept the last number: 1 or 2)
	NANO_GLABEL_SYS_FULL=`mount | grep " / " | cut -d'/' -f4 \
	| cut -d' ' -f1`

	# Get the disk name using its label
	NANO_DRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} \
	| awk '{print $3}' | cut -d's' -f1`

	# Get the full disk name
	NANO_FULLDRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} \
	| awk '{print $3}'`

	# Check and set final variable
	DST_SLICE=0

	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s1"` ]; then 
    		DST_SLICE=2
    		SRC_SLICE=1
	fi
	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s2"` ]; then                
    		DST_SLICE=1
    		SRC_SLICE=2
	fi

	[ $DST_SLICE = 0 ] && die "Can't detect active slice"
	
	# Check if old system was good
	if [ -e /dev/${NANO_DRIVE}s${DST_SLICE}a ]; then
		fsck_ffs -n /dev/${NANO_DRIVE}s${DST_SLICE}a || 
		die "ERROR: Missing or fsck problem on the previous system slice"
	else
		die "ERROR: This system was never upgraded"
	fi

	echo -n "Warning: Are you sure to revert to the previous release ? (y/n)"
	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
       		read USER_CONFIRM <&1
	done
	[ "$USER_CONFIRM" = "n" ] && exit 0

	# Need to compare some files between the old and new partition
	[ -d /tmp/sysupgrade ] || mkdir /tmp/sysupgrade

	#   Adapt fstab of the old system
	sed -i "" "s/${NANO_GLABEL_SYS}s${SRC_SLICE}a/${NANO_GLABEL_SYS}s${DST_SLICE}a/g" /etc/fstab

	# Save the config file that include the fstab
	mount /cfg || die "ERROR: Cant't mount /cfg"
	if ! cp /etc/fstab /cfg; then
    		umount /cfg
		die "ERROR: Can't save fstab"
	fi
	umount /cfg || die "ERROR: Can't umount /cfg"
	case `uname -m` in
	i386|amd64)
		boot0cfg -s ${DST_SLICE} -t 18 -v ${NANO_DRIVE} ||
		   die "ERROR: Can't update FreeBSD bootloader"
           
		gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE} ||
		   die "ERROR: Can't update active partition"
                ;;
        arm)
                echo "arm upgrade script not tested!"   
                gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE} ||
                   die "ERROR: Can't update active partition"
                ;;
        sparc64)
                echo "You need to configure OBP for booting on"
                ;;
	esac

# Log
echo "BSDRP system rollback complete"
logger BSDRP system rollback complete

}

# Check if cfg was modified
check_cfg () {
	# Testing /etc/rc.conf
	sh /etc/rc.conf || die "There is an error in /etc/rc.conf file"
	echo "Checking if configuration is saved..."
	# Don't know why I can't test the exist value of config diff quit in my if
	set +e
	config diff quiet
	[ $? -eq 1 ] && ask_save
	set -e
}

# Reboot
sys_reboot () {
	check_cfg
	echo "Rebooting..."
	# Never use reboot(8) under FreeBSD !
	shutdown -r now
}

# Halt
sys_halt () {
	check_cfg
	echo "Power halting..."
	# Never use halt under FreeBSD !
	shutdown -p now
}

###################
## Main function ##
###################

# Get options passed by user
if [ $# -eq 0 ]; then
	FIRST_OPTION=""
	SECOND_OPTION=""
	THIRD_OPTION=""
	usage
	exit 0
fi

FIRST_OPTION="$1"

if [ $# -ge 2 ]; then
	SECOND_OPTION="$2"
else
	SECOND_OPTION=""
fi
if [ $# -ge 3 ]; then
	THIRD_OPTION="$3"
else
	THIRD_OPTION=""
fi

case "$FIRST_OPTION" in
	check-vm)
        check_vm
        ;;
	dual-console)
		dual_console ${SECOND_OPTION}
		;;
	expand-data-slice)
		expand_data_slice
		;;
	halt|stop)
		sys_halt
		;;
    help|h)
        usage
        ;;
	install)
		install ${SECOND_OPTION}
		;;
    integrity)
        integrity
        ;;
	reboot|reload)
		sys_reboot
		;;
	rollback)
		rollback
		;;
	*)
		usage
		;;
esac
