#!/bin/sh

# $FreeBSD: ports/net/bird/files/bird.in,v 1.1 2010/06/28 07:58:07 pav Exp $
#
# PROVIDE: bird
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# bird_enable (bool):   Set to NO by default.
#               Set it to YES to enable bird.
# bird_config (path):   Set to /usr/local/etc/bird.conf
#               by default.
#

. /etc/rc.subr

name="bird"
rcvar=${name}_enable

command=/usr/local/sbin/${name}

load_rc_config $name

: ${bird_enable="NO"}
: ${bird_config="/usr/local/etc/bird.conf"}

command_args="-s /var/run/bird.ctl -c $bird_config"

run_rc_command "$1"
